### ISSUE TITLE
Cannot find module <name> or its corresponding type declarations.

### ISSUE THREAD

**Issue by wojtekKrol** [andoshin11/typescript-error-reporter-action#17]
I use webstorm which can simplify code by e.g. making path shorter
![image](https://user-images.githubusercontent.com/64773541/100164879-22a50680-2eb9-11eb-9e8e-6619204d2038.png)

Tree of my project:

```
server/src
├── routes
│   └── userRouter.ts
└── types
    ├── customRequestResponse.ts
    └── user.ts
```
`userRouter.ts`
```
import { CustomRequestWithQuery } from '../types/customRequestResponse';
import { UserAuth, UserLoginQuery } from '../types/user';
```

Now webstorm can simplify these import to:
```
import { CustomRequestWithQuery } from 'customRequestResponse';
import { UserAuth, UserLoginQuery } from 'user';
```

which genere error
![image](https://user-images.githubusercontent.com/64773541/100164806-ef627780-2eb8-11eb-925e-f7a5db4ea389.png)

**Comment by ypresto** [comment]
Check your baseUrl in tsconfig.json? In my environment it just works.
